# Generated by Django 2.1.5 on 2019-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('w_test', models.CharField(max_length=100)),
                ('idate', models.DateTimeField(verbose_name='insertedtime')),
            ],
        ),
    ]
